# Generated by Django 3.2.18 on 2023-03-11 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='on_trial',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='paid_until',
        ),
    ]
