version: "3.8"
services:
  postgres:
    image: postgres:15.2-alpine
    container_name: django_tenants_db
    healthcheck:
      test: nc -z localhost 5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_PORT=${DB_PORT}
    ports:
      - "5433:5432"
    expose:
      - "5432"

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./restaurant_saas/staticfiles:/home/app/staticfiles

  local:
    build: .
    image: django-webapp:0.0.1
    depends_on:
      - postgres
      - nginx
    env_file:
      - .env
    environment:
      - DEBUG=1
      - DB_HOST=postgres
    command:
      - /bin/sh
      - -c
      - |
        while ! nc -q 1 postgres 5432 </dev/null; do sleep 5; done
        chmod u+rx setup_django.sh
        ./setup_django.sh
    container_name: django_multi_tenant
    expose:
      - "8000"

volumes:
  staticfiles: