version: "3.8"
services:
  postgres:
    image: postgres:15.2-alpine
    container_name: django_tenants_db
    healthcheck:
      test: nc -z localhost 5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_PORT=${DB_PORT}
    ports:
      - "5433:5432"

  nginx:
    build:
      context: ./nginx
    depends_on:
      - local
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - staticfiles:/home/app/staticfiles

  local:
    image: django-webapp:0.0.1
    build:
      context: .
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - DEBUG=1
      - DB_HOST=postgres
    command:
      - /bin/sh
      - -c
      - |
        while ! nc -q 1 postgres 5432 </dev/null; do sleep 5; done
        python3 manage.py collectstatic --noinput
        python3 manage.py makemigrations && python3 manage.py migrate
        python3 create_public_tenant.py
        gunicorn restaurant_saas.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - staticfiles:/usr/src/app/staticfiles
    container_name: django_multi_tenant

volumes:
  staticfiles: