# Generated by Django 3.2.18 on 2023-03-16 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tenantuser_tenants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantuser',
            name='tenants',
        ),
    ]
